<!DOCTYPE html>
<html>
	<head>
	<meta charset="utf-8" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta content=" English">
	<meta name="description" content ="IV Holiday - book your holiday here.">
	<meta name="keywords" content="holiday,journey,book holiday,low price">
	<meta name="Author" content="www.ivholiday.com">
	<meta name="Copyright " content="Copyright (c) Iv">
	<meta name="town" content="Pazardjik">
	<meta name="distribution" content="Global">
	<title>IV Holiday</title>
	<link href="/loader.php?file=css/styles.css" rel="stylesheet" type="text/css" href="css/styles.css">
	<link href="/loader.php?file=css/style_nav.css" rel="stylesheet" type="text/css" href="css/style_nav.css">
	
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
	<link href="http://localhost:10120/loader.php?file=css/bootstrap.min.css" rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
	<!-- Responsive Design-->
	</head>
	
	<body>
		<div class="main">
		<div class="container">
	
		<header>
			<div id="searchBox">
				<div id="searchBoxBorder"></div>
					<div align="center">
						<h4> Everything you need is here ... </h4>
					</div>
				</div>
			
			<div id="logo">
				<img src="/loader.php?file=img/logo.png" width="200" height="150" alt="Logo" />
			</div>	
			
			<div id="loginMenu">
					<div id="slider">
					<div id="searchBoxBorder"></div>

						<ul class="inline" align="center">
							<li><a href='#'><h5>HOME</h5></a></li>
							<li><a href='#'><h5>LOGIN</h5></a></li>
							<li><a href='#'><h5>REGISTRATION</h5></a></li>
							<li><a href='#'><h5>CART</h5></a></li>
						</ul>
						
					</div>
				</div>

				<div style="clear: both"></div>

				<nav>
					<div class="navbar navbar-inverse">
						 <div class="navbar-inner">
							<div class="container" >
						 
							  <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
							  <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							  </a>
						 
							  <!-- Be sure to leave the brand out there if you want it shown -->
							  <ul class="nav" >
								  <li><a href="#">HOME</a></li>
								  <li><a href="#">ABOUT US</a></li>
								  <li><a href="#">OUR DESTINATIONS</a></li>
								  <li><a href="#">BOOK HOLIDAY</a></li>
								  <li><a href="#">YOUR CART</a></li>
								  <li><a href="#">CONTACT US</a></li> 
							 </ul>
							 
							 <form class="navbar-search pull-left">
								<input type="text" class="search-query" placeholder="Search">
							</form>
							
							<!-- Everything you want hidden at 940px or less, place within here -->
							  
							<!-- .nav, .navbar-search, .navbar-form, etc -->
							  <
							</div>
						  </div>
						</div>
				</nav>
				
			</header>

			<div id="myCarousel" class="carousel slide">
			  <ol class="carousel-indicators">
				<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
				<li data-target="#myCarousel" data-slide-to="1"></li>
				<li data-target="#myCarousel" data-slide-to="2"></li>
			  </ol>
			  <!-- Carousel items -->
			  <div class="carousel-inner">
				<div class="active item"><img src="/loader.php?file=img/1.jpg" width="1000" alt="Slider"></div>
				<div class="item"><img src="/loader.php?file=img/2.jpg" width="1000" alt="Slider"></div>
				<div class="item"><img src="/loader.php?file=img/3.jpg" width="1000" alt="Slider"></div>
			  </div>
			  <!-- Carousel nav -->
			  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
			  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
			</div>
			
			<div id="content">
				<?php echo $this->content; ?>
			</div>
		
		
			<footer>
				<div id="borderSolid">
					<ul class="thumbnails">
					  <li class="span4">
					  <div  align="center">
						<h4> Methods of payment</h4>
						<p>PayPal payment<p><img src="/loader.php?file=img/cards.jpg" width="140" alt="Methods of payment"></p></p>
						<p>Cash on Arrival</p>
						<p>Payment by bank transfer</p>
					  </div>
					  </li>
					  
					  <li class="span4"> 
					  <div align="center">
					  <h4> About us</h4>
					  <p> <a href="#">
						<img src="/loader.php?file=img/logo.png" width="200" height="100" alt="About Us" />
						</a>
					  </p>
					  </div>
					  </li>
					  
					  
					  <li class="span4">
					  <div align="center">
					  <div id="slider">
					  <h4> Help for our clients</h4> 
						<p><a href="#">How to book holiday?</a></p>
						<p><a href="#">How to pay?</a></p>
						<p><a href="#">How to refuse reservation?</a></p>
						<p><a href="#">Contact us</a></p>	  
					  </div>
					  </div>
					  </li>
					</ul>
				</div>		
			</footer>
		</div>
		</div>

		<script src="http://code.jquery.com/jquery.js"></script>
		<script src="/loader.php?file=js/bootstrap.min.js" ></script>

	</body>
</html>
